USE WATERQUALITY

--SELECT DATAENTRYNUMBER, DATE, SITEID, STREAMNAME, Conductivity
--FROM WORKDATA
--ORDER BY SITEID, Conductivity

--UPDATE WORKDATA
--SET FLOW = (SELECT ROUND(AVG(FLOW),3)
--			FROM WORKDATA
--			WHERE SITEID = 12 AND FLOW IS NOT NULL
--			GROUP BY SITEID)
--WHERE SITEID = 12 AND FLOW IS NULL

--UPDATE WORKDATA
--SET FLOW = (SELECT ROUND(AVG(FLOW),3)
--			FROM WORKDATA
--			WHERE SITEID = 14 AND FLOW IS NOT NULL
--			GROUP BY SITEID)
--WHERE SITEID = 14 AND FLOW IS NULL

--DELETE WORKDATA
--WHERE SITEID = 16

--UPDATE WORKDATA
--SET FLOW2 = (SELECT ROUND(AVG(FLOW2),3)
--			FROM WORKDATA
--			WHERE SITEID = 14 AND FLOW2 IS NOT NULL
--			GROUP BY SITEID)
--WHERE SITEID = 14 AND FLOW2 IS NULL

--UPDATE WORKDATA
--SET FLOW2 = (SELECT ROUND(AVG(FLOW2),3)
--			FROM WORKDATA
--			WHERE SITEID = 12 AND FLOW2 IS NOT NULL
--			GROUP BY SITEID)
--WHERE SITEID = 12 AND FLOW2 IS NULL

--UPDATE WORKDATA
--SET PERCSAT = (SELECT ROUND(AVG(PERCSAT),3)
--			FROM WORKDATA
--			WHERE SITEID = 4 AND PERCSAT IS NOT NULL
--			GROUP BY SITEID)
--WHERE SITEID = 4 AND PERCSAT IS NULL

--UPDATE WORKDATA
--SET PERCSAT = (SELECT ROUND(AVG(PERCSAT),3)
--			FROM WORKDATA
--			WHERE PERCSAT IS NOT NULL)
--WHERE SITEID = 15 AND PERCSAT IS NULL

--DECLARE @SID INT
--SET @SID = 1
--WHILE @SID < 15
--BEGIN
--	UPDATE WORKDATA
--	SET Conductivity = (SELECT ROUND(AVG(CONDUCTIVITY), 3)
--						FROM WORKDATA
--						WHERE SITEID = @SID AND Conductivity IS NOT NULL
--						GROUP BY SITEID)
--	WHERE SITEID = @SID AND Conductivity IS NULL
--	SET @SID = @SID + 1
--END

--DECLARE @SID2 INT
--SET @SID2 = 1
--WHILE @SID2 < 15
--BEGIN
--	UPDATE WORKDATA
--	SET ECOLI = (SELECT ROUND(AVG(ECOLI), 0)
--						FROM WORKDATA
--						WHERE SITEID = @SID2 AND ECOLI IS NOT NULL
--						GROUP BY SITEID)
--	WHERE SITEID = @SID2 AND EColi IS NULL
--	SET @SID = @SID + 1
--END

--UPDATE WORKDATA
--SET EColi = (SELECT ROUND(AVG(ECOLI), 0)
--			 FROM WORKDATA
--			 WHERE ECOLI IS NOT NULL)
--WHERE SITEID = 15 AND ECOLI IS NULL


SELECT Flow2
FROM WORKDATA
ORDER BY FLOW2 DESC

